name: Quests
version: 1.0.0
description: Make quests!
author: Ultimate 
main: main.java.me.ultimate.Q.Quests
depend: [Citizens]
softdepend: [EpicBoss]

commands:
  quests:
    description: Admin quest command
    usage: /quests
  quest:
    description: Basic quest command
    usage: /quest
